CREATE TABLE HOTELS(
  hotel_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  hotel_name VARCHAR(16) NOT NULL,
  price VARCHAR(10) NOT NULL,
  availability VARCHAR(5) NOT NULL
);

CREATE TABLE GUESTS(
  guest_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  guest_name VARCHAR(64),
  gender VARCHAR(5),
  confirmation_number BIGINT
);

CREATE TABLE RESERVATION(
  confirmation_number BIGINT AUTO_INCREMENT PRIMARY KEY,
  hotel_id BIGINT NOT NULL,
  checkin VARCHAR NOT NULL,
  checkout VARCHAR NOT NULL
);

ALTER TABLE RESERVATION ADD FOREIGN KEY (hotel_id) REFERENCES HOTELS(hotel_id);
ALTER TABLE GUESTS ADD FOREIGN KEY (confirmation_number) REFERENCES RESERVATION(confirmation_number)
